# Generated by Django 5.0.1 on 2026-03-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organization',
            field=models.BooleanField(default=False, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название организации'),
        ),
    ]
