# Generated by Django 5.0.1 on 2026-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization_contact',
            field=models.CharField(blank=True, max_length=500, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_description',
            field=models.TextField(blank=True, verbose_name='Описание организации'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_members',
            field=models.TextField(blank=True, verbose_name='Участники организации'),
        ),
    ]
