# Generated by Django 5.0.1 on 2026-03-07 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_organization_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_organization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_members',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_name',
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название сообщества')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание сообщества')),
                ('members', models.TextField(blank=True, verbose_name='Участники сообщества')),
                ('contact_info', models.CharField(blank=True, max_length=500, verbose_name='Контактная информация')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='communities/', verbose_name='Аватар сообщества')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
                ('members_users', models.ManyToManyField(blank=True, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['name'],
            },
        ),
    ]
