# Generated by Django 5.0.1 on 2026-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_is_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_community',
            field=models.BooleanField(default=False, verbose_name='Может создавать сообщества'),
        ),
    ]
