# Generated by Django 5.0.1 on 2026-03-09 08:55

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_can_create_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён телефон (дата)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, default=users.models._default_token, max_length=6),
        ),
        migrations.CreateModel(
            name='PhoneVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=users.models._default_token, max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=users.models._default_expires_at)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен подтверждения телефона',
                'verbose_name_plural': 'Токены подтверждения телефона',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.AddIndex(
            model_name='phoneverificationtoken',
            index=models.Index(fields=['token'], name='users_phone_token_204e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationtoken',
            index=models.Index(fields=['user', 'created_at'], name='users_phone_user_id_54a96c_idx'),
        ),
    ]
