# Generated by Django 5.0.1 on 2026-03-10 15:10

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_telegramverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(db_index=True, default=users.models._default_verification_code, max_length=8)),
                ('reset_token', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=users.models._default_expires_at)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Верификация сброса пароля',
                'verbose_name_plural': 'Верификации сброса пароля',
                'indexes': [models.Index(fields=['verification_code'], name='users_passw_verific_aa885a_idx'), models.Index(fields=['user', 'created_at'], name='users_passw_user_id_197987_idx')],
            },
        ),
    ]
