# Generated by Django 5.0.1 on 2026-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_passwordresetverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_data_processing',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
