# Generated by Django 5.0.1 on 2026-08-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_accepted_data_processing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phoneverificationtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegramverificationtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetVerification',
        ),
        migrations.DeleteModel(
            name='PhoneVerificationToken',
        ),
        migrations.DeleteModel(
            name='TelegramVerificationToken',
        ),
    ]
