# Generated by Django 5.0.1 on 2026-08-07 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_membership_roles(apps, schema_editor):
    """
    Copy the old implicit members_users M2M rows into CommunityMembership
    before the field below switches to an explicit `through` model (which
    would otherwise leave the new table empty). Creator -> owner, everyone
    else already in members_users -> member.
    """
    Community = apps.get_model('users', 'Community')
    CommunityMembership = apps.get_model('users', 'CommunityMembership')

    for community in Community.objects.all():
        existing_member_ids = set(community.members_users.values_list('id', flat=True))

        CommunityMembership.objects.update_or_create(
            community=community,
            user_id=community.created_by_id,
            defaults={'role': 'owner'},
        )

        for user_id in existing_member_ids:
            if user_id == community.created_by_id:
                continue
            CommunityMembership.objects.update_or_create(
                community=community,
                user_id=user_id,
                defaults={'role': 'member'},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_passwordresetverification_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('moderator', 'Модератор'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Вступил')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие в сообществе',
                'verbose_name_plural': 'Участия в сообществах',
            },
        ),
        migrations.RunPython(backfill_membership_roles, noop_reverse),
        migrations.RemoveField(
            model_name='community',
            name='members_users',
        ),
        migrations.AddField(
            model_name='community',
            name='members_users',
            field=models.ManyToManyField(blank=True, related_name='communities', through='users.CommunityMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='communitymembership',
            constraint=models.UniqueConstraint(fields=('community', 'user'), name='unique_community_membership'),
        ),
    ]
