# Generated by Django 5.0.1 on 2026-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_communitymembership_alter_community_members_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yandex_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Яндекс'),
        ),
    ]
