# Generated by Django 5.0.1 on 2026-08-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_yandex_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AddField(
            model_name='community',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
