# Generated by Django 5.0.1 on 2025-12-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_video_url_series_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер'),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
