# Generated by Django 5.0.1 on 2025-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_url_series_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Актёры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Режиссёр'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Продюсер'),
        ),
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Актёры'),
        ),
        migrations.AddField(
            model_name='series',
            name='age_rating',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Режиссёр'),
        ),
        migrations.AddField(
            model_name='series',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Продюсер'),
        ),
    ]
