# Generated by Django 5.0.1 on 2026-01-26 19:26

import django.db.models.deletion
from django.utils.text import slugify
from django.conf import settings
from django.db import migrations, models


def _generate_unique_slug(model, base_slug):
    slug = base_slug
    suffix = 1
    while model.objects.filter(slug=slug).exists():
        slug = f"{base_slug}-{suffix}"
        suffix += 1
    return slug


def populate_slugs(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Series = apps.get_model('movies', 'Series')
    Genre = apps.get_model('movies', 'Genre')

    for genre in Genre.objects.filter(slug__isnull=True):
        base_slug = slugify(genre.name) or 'genre'
        genre.slug = _generate_unique_slug(Genre, base_slug)
        genre.save(update_fields=['slug'])

    for movie in Movie.objects.filter(slug__isnull=True):
        base_slug = slugify(movie.title) or 'movie'
        movie.slug = _generate_unique_slug(Movie, base_slug)
        movie.save(update_fields=['slug'])

    for series in Series.objects.filter(slug__isnull=True):
        base_slug = slugify(series.title) or 'series'
        series.slug = _generate_unique_slug(Series, base_slug)
        series.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_actors_movie_age_rating_movie_director_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отзыв о фильме',
                'verbose_name_plural': 'Отзывы о фильмах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeriesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отзыв о сериале',
                'verbose_name_plural': 'Отзывы о сериалах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='series',
            name='views',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный фильм',
                'verbose_name_plural': 'Избранные фильмы',
            },
        ),
        migrations.CreateModel(
            name='FavoriteSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный сериал',
                'verbose_name_plural': 'Избранные сериалы',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='movies.genre', verbose_name='Жанры'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active'], name='movies_movi_is_acti_00ce83_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='movies_movi_year_82d175_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_active'], name='movies_seri_is_acti_434c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['year'], name='movies_seri_year_7a45eb_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['rating'], name='movies_seri_rating_997886_idx'),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seriesreview',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.series'),
        ),
        migrations.AddField(
            model_name='seriesreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favoritemovie',
            index=models.Index(fields=['user', 'movie'], name='movies_favo_user_id_33a055_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='favoriteseries',
            index=models.Index(fields=['user', 'series'], name='movies_favo_user_id_4ab483_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteseries',
            unique_together={('user', 'series')},
        ),
        migrations.AddIndex(
            model_name='moviereview',
            index=models.Index(fields=['movie', 'is_active'], name='movies_movi_movie_i_14792d_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesreview',
            index=models.Index(fields=['series', 'is_active'], name='movies_seri_series__0d150e_idx'),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
