# Generated by Django 5.0.1 on 2026-01-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_show_favorites_reviews'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoriteshow',
            new_name='movies_favo_user_id_80f553_idx',
            old_name='movies_favo_user_id_e9db18_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='movies_show_is_acti_ca0c70_idx',
            old_name='movies_show_is_acti_8b7c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='movies_show_year_20e104_idx',
            old_name='movies_show_year_4e97e9_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='movies_show_rating_5cee45_idx',
            old_name='movies_show_rating_f38f9f_idx',
        ),
        migrations.RenameIndex(
            model_name='showreview',
            new_name='movies_show_show_id_2b56f5_idx',
            old_name='movies_show_show_i_4d32a0_idx',
        ),
    ]
