# Generated by Django 5.0.1 on 2026-03-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_movies_favo_user_id_e9db18_idx_movies_favo_user_id_80f553_idx_and_more'),
        ('users', '0006_userprofile_organization_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('organization', models.ForeignKey(limit_choices_to={'is_organization': True}, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.show')),
            ],
            options={
                'verbose_name': 'Проект организации',
                'verbose_name_plural': 'Проекты организаций',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationproject',
            constraint=models.CheckConstraint(check=models.Q(('movie__isnull', False), ('series__isnull', False), ('show__isnull', False), _connector='OR'), name='at_least_one_project'),
        ),
    ]
