# Generated by Django 5.0.1 on 2026-03-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_organizationproject_and_more'),
        ('users', '0007_remove_userprofile_is_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.community')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.show')),
            ],
            options={
                'verbose_name': 'Проект сообщества',
                'verbose_name_plural': 'Проекты сообществ',
            },
        ),
        migrations.DeleteModel(
            name='OrganizationProject',
        ),
        migrations.AddConstraint(
            model_name='communityproject',
            constraint=models.CheckConstraint(check=models.Q(('movie__isnull', False), ('series__isnull', False), ('show__isnull', False), _connector='OR'), name='at_least_one_project'),
        ),
    ]
